logger:
  level: "INFO"

server:
  host: "0.0.0.0"
  port: "8080"
  grpcHost: "0.0.0.0"
  grpcPort: "50051"

storage:
  type: "sql"

database:
  dsn: "host=postgres port=5432 user=calendar password=calendar dbname=calendar sslmode=disable"

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"
  queue: "calendar_notifications"

schedule:
  scanInterval: "1m"
  cleanupInterval: "24h"
