logger:
  level: "INFO"

server:
  host: "localhost"
  port: "8080"
  grpcHost: "localhost"
  grpcPort: "50051"

storage:
  type: "sql"  # "memory" or "sql"

database:
  dsn: "host=localhost port=5432 user=calendar password=calendar dbname=calendar sslmode=disable"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue: "calendar_notifications"

schedule:
  scanInterval: "1m"
  cleanupInterval: "24h"