logger:
  level: "INFO"

server:
  host: "localhost"
  port: "8080"
  grpc_host: "localhost"
  grpc_port: "50051"

storage:
  type: "memory"  # "memory" or "sql"

database:
  dsn: "host=localhost port=5432 user=calendar password=calendar dbname=calendar sslmode=disable"